#!/bin/sh

# main 브랜치에 push 하지 못하도록 방지
FORBIDDEN="refs/heads/main"
while read local_ref local_sha remote_ref remote_sha
do
    echo $FORBIDDEN
    echo $remote_ref
    if [ $remote_ref = $FORBIDDEN ] ; then
      echo "Not allowed to push into ${FORBIDDEN}"
	    exit 1
    fi	
done

# test & lint
cd $(dirname ${BASH_SOURCE[0]}) && cd ../  # shell script의 주소로 이동후 프로젝트 루트로 이동
SCRIPT_DIR=`pwd` # shell script의 주소 저장

./gradlew check
if [ $? -eq 0 ]; then
  echo "================================"
  echo "Code style check has successfully completed"
  echo "================================"
else
  echo "================================"
  echo "Fail to check Code style"
  echo "================================"
  exit 1
fi
