version: '3'

services:

  mysql:
    image: mysql:8.0.25
    platform: linux/x86_64
    container_name: bluedelivery-mysql
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  kafka:
    image: 'confluentinc/cp-kafka:6.2.0'
    container_name: bluedelivery-kafka
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_INTERNAL://bluedelivery-kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:29092,PLAINTEXT_INTERNAL://bluedelivery-kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPICS: "order-status:3:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - ./docker/kafka/data:/var/lib/kafka/data

  zookeeper:
    image: zookeeper:3.5
    container_name: bluedelivery-zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./docker/zookeeper/data:/data
      - ./docker/zookeeper/logs:/datalog

  redis:
    image: redis:6.2.4
    container_name: bluedelivery-redis
    ports:
      - "6379:6379"
    restart: always


############################## 모니터링 도구는은 추후에 재구성 ##############################

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
#    container_name: bluedelivery-elasticsearch
#    ports:
#      - 9200:9200
#    environment:
#      - node.name=elasticsearch
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=elasticsearch
#      - cluster.initial_master_nodes=elasticsearch
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./docker/es/data:/usr/share/elasticsearch/data
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.14.0
#    container_name: bluedelivery-kibana
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#
#  elastic-apm:
#    image: docker.elastic.co/apm/apm-server:7.14.0
#    container_name: bluedelivery-elastic-apm
#    ports:
#      - 8200:8200
#    volumes:
#      - ./docker/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml"
#    environment:
#      output.elasticsearch.hosts: '["elasticsearch:9200"]'
#
#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    container_name: bluedelivery-kafdrop
#    restart: "no"
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BROKERCONNECT: "kafka:9092"
#      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
#    depends_on:
#      - "bluedelivery-kafka"

######################################################################################

#  nginx:
#    image: nginx:1.21.0
#    volumes:
#      - ./docker/nginx/conf.d:/etc/nginx/conf.d
#    ports:
#      - 8080:80
