spring:

  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://${db.hostname}:3306/delivery
    user: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  redis:
    host: ${redis.hostname}
    password:
    port: 6379

db:
  hostname: db-mysql # Docker container에서 localhost는 was 자신이 되기때문에 docker db 호스트 이름을 적어줘야함.
redis:
  hostname: redis
