spring:
  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/delivery
    user: root
    password:
    baseline-on-migrate: true
    ignore-ignored-migrations: true
    clean-on-validation-error: true

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    password:
    port: 6379
