spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.URL}/blue_delivery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  redis:
    host: ${REDIS.HOST}
    port: ${REDIS.PORT}
  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP_SERVERS}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: # 보여주고 싶은 application 정보들
          - "info"
          - "health"
          - "flyway"
          - "metrics"
          - "scheduledtasks"
      base-path: /application
      path-mapping:
        health: healthcheck

  health:
    diskspace:
      enabled: false

  endpoint:
    health:
      show-details: always #Application에서 의존하고 있는 시스템의 healthCheck 정보 포함(mysql, redis 등)

  info: # info에 git 정보 포함
    git:
      mode: simple # simple or pull

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package:
    com.bluedelivery.domain.shop,
    com.bluedelivery.domain.category,
    com.bluedelivery.application.shop.businesshour,
    com.bluedelivery.shop.domain.closingday,
    com.bluedelivery.domain.suspension,
    com.bluedelivery.user.domain,
    com.bluedelivery.utility,
    org.apache.ibatis.type

logging:
  config: classpath:logback/logback-spring.xml
