spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      auto-offset-reset: latest

# variables
DB:
  URL: localhost:13306
  USERNAME: root
  PASSWORD: ""
REDIS:
  HOST: localhost
  PORT: 16379
KAFKA:
  BOOTSTRAP_SERVERS: localhost:29092

